:data-uri:
:toc:

[[install-minishift]]
= Install Minishift

Minishift is a tool that helps you run OpenShift locally by launching a single-node OpenShift cluster inside a virtual machine.
With Minishift you can try out OpenShift or develop with it, day-to-day, on your local machine.

[[prerequesites]]
== Prerequisites

Minishift requires a hypervisor to start the virtual machine on which the OpenShift cluster is provisioned.
Make sure that the hypervisor of your choice is installed and enabled on your system before you start Minishift.

.Hypervisor Options
NOTE: Depending on your host OS, you have the choice of installing different hypervisors.

Depending on your host OS, you have the choice of the following hypervisors:

* Mac OS X
  - https://github.com/mist64/xhyve[xhyve] (default)
  - https://www.virtualbox.org/wiki/Downloads[VirtualBox]
  - https://www.vmware.com/products/fusion[VMware Fusion]

* GNU/Linux
  - https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine[KVM] (default)
  - https://www.virtualbox.org/wiki/Downloads[VirtualBox]

* Windows
  - https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v[Hyper-V] (default)
  - https://www.virtualbox.org/wiki/Downloads[VirtualBox]


[[manual-install]]
== Manual Install
. Download the archive for your operating system from the {{MINISHIFT_RELEASES_PAGE}}[Minishift releases page] and unpack it.
. Copy the contents of the directory to your preferred location.
. Add the `minishift` binary to your `PATH` environment variable.

WARNING: On Windows operating system, you need to execute the `minishift` binary from the drive containing your `%USERPROFILE%`` directory.

[[automated-install]]
== Automated Install

On OS X you can also use https://caskroom.github.io/[Homebrew Cask] to install the stable version of Minishift.

[source,sh]
----
brew cask install minishift
----

[[start-minishift]]
== Start minishift
. Run the following command to start your OpenShift instance.
+
[source,sh]
----
minishift start --memory=4096
----
+
. Login as administrator executing:
+
[source,sh]
----
oc login -u system:admin
----
